services:
  bot:
    build: .
    container_name: stravabot
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - ID_CLIENTE=${ID_CLIENTE}
      - SECRETO_CLIENTE=${SECRETO_CLIENTE}
      - S_TOKEN_ACTUALIZACION=${S_TOKEN_ACTUALIZACION}
      - M_TOKEN_ACCESO=${M_TOKEN_ACCESO}
      - MASTODON_API=${MASTODON_API}
      - ENTORNO=${ENTORNO}